REPLAY-1347 Improve image classification
DataDog/dd-sdk-ios pull request #1200
Opened 2023-03-08 16:26 UTC by maciejburda

### What and why?

Improves image classification to get only contextual images into account.

### How?

It's accomplished by simplification of `ImageDataProvider` and moving some of it's responsibility to `UIImageViewRecorder` which enables reusability of this recorder.

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

2023-03-08 16:26 UTC, maciejburda commented on DatadogSessionReplay/Sources/Recorder/Utilities/ImageDataProvider.swift
> +    func compressToTargetSize(_ targetSize: Int) -> Data {
improve

2023-03-10 14:15 UTC, maciejburda commented on DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewWireframesBuilderTests.swift
> +class UIImageViewWireframesBuilderTests: XCTestCase {
Coverage here could be increased. Maybe we could discuss the plan for testing more elaborate wireframes builders.

2023-03-10 14:16 UTC, maciejburda commented on DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewWireframesBuilderTests.swift
> +class MockImageDataProvider: ImageDataProvider {
we should probably move it somewhere more suitable

2023-03-21 12:14 UTC, ncreated requested changes
It looks OK 👌 , but causes regression compared to `develop` so we need to improve it. Some images result with base64 values that exceed the SDK core's max _event size_. In result we do not send replay.

On preventing such regression in the future - I think we need to consider adding integration tests of the same fashion as we have in RUM SDK (sending SR payload to HTTP server and asserting its delivery). Let's discuss it on daily.

2023-03-24 09:38 UTC, maciejburda commented on DatadogSessionReplay/Tests/Recorder/ViewTreeSnapshotProducer/ViewTreeSnapshot/NodeRecorders/UIImageViewWireframesBuilderTests.swift
> +class UIImageViewWireframesBuilderTests: XCTestCase {
I like that. I'll keep these until we have snapshot in place. I'll describe the work in the ticket.

2023-03-27 08:31 UTC, ncreated approved these changes
Looks good 👌 💪

2023-03-27 09:27 UTC, merged