RUMM-2922 Introduce `RUM.enable(with:in:)` API for 2.x
DataDog/dd-sdk-ios pull request #1312
Opened 2023-06-19 11:45 UTC by ncreated

### What and why?

// TBD

### How?

// TBD

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [x] Run integration tests
- [ ] Run smoke tests

2023-06-19 13:23 UTC, ncreated commented on DatadogRUM/Sources/Feature/DatadogRUMFeature.swift
>  internal final class DatadogRUMFeature: DatadogRemoteFeature {
I'll resolve it in next PR - `RUMM-2922` is not yet over.

2023-06-19 13:25 UTC, ncreated commented on DatadogRUM/Sources/Instrumentation/RUMInstrumentation.swift
No real changes in RUM instrumentation - just aligning things in this file for more coherence. Notable change is the removal of `enable()` + `deinitialize()` APIs, as now this component manages instrumentation between `init()` and `deinit()`.

2023-06-19 13:26 UTC, ncreated commented on DatadogRUM/Sources/RUMConfiguration.swift
Real work in this file will happen in next PR. Here just doing partial step.

2023-06-19 13:36 UTC, ncreated commented on Tests/DatadogTests/Datadog/RUM/RUMFeatureTests.swift
> -        let randomVariant: String = .mockAny()
Moved to RUM's `RequestBuilderTests`. The only difference in this test and the next one is adding `variant` in URL query. Works much better if tested in pure unit-fashion.

2023-06-19 16:02 UTC, maxep requested changes
Nice work, it's taking shape!

I've left to remove the `RUMMonitorInternalProtocol` and the `monitorFactory`, but maybe I'm missing some needs for further PRs. LMK!

2023-06-20 06:54 UTC, ncreated commented on DatadogRUM/Sources/Feature/DatadogRUMFeature.swift
> +    let monitor: RUMMonitorProtocol & RUMMonitorInternalProtocol
It made some sense when I started this task 🙃, but I agree it doesn't bring anything right now. Removed ✅, it's `monitor: Monitor` again.

2023-06-20 06:57 UTC, ncreated commented on DatadogRUM/Sources/Feature/DatadogRUMFeature.swift
> +    ) throws {
Agree 👍, let's keep it simple, removed ✅. Especially that soon, with [RUMM-3151](https://datadoghq.atlassian.net/browse/RUMM-3151) we won't need to patch `Monitor` dependencies anymore 🙌.

2023-06-20 11:38 UTC, maxep approved these changes
🚀

2023-06-20 16:51 UTC, merged