REPLAY-1805 Player side placeholder
DataDog/dd-sdk-ios pull request #1326
Opened 2023-06-23 10:38 UTC by maciejburda

### What and why?

Adds and utilises new type of wireframe that represents placeholders.

### How?

A brief description of implementation details of this PR.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

2023-06-23 10:40 UTC, maciejburda commented on DatadogSessionReplay/Sources/Processor/SRDataModelsBuilder/WireframesBuilder.swift
> +            isEmpty: false,
add deprecated comment info

2023-06-23 20:48 UTC, buraizu approved these changes

2023-06-26 09:00 UTC, ncreated requested changes
Multiple blockers:
- **No tests**: wireframes diffing and mutations are tested in [Diff+BSRWireframesTests.swift](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogSessionReplay/Tests/Processor/Diffing/Diff%2BSRWireframesTests.swift) and it must be no different for `placeholder` wireframe (please add also tests for `image` wireframe that was introduced [earlier](https://github.com/DataDog/dd-sdk-ios/pull/1144/files) with no tests)
- **SRSnapshotTests broken**: the project doesn't build because it needs to be updated with rendering of `placeholder` wireframes.
- **Strong regression**: I'm observing critical regression on this branch when testing manually. When adding unsupported view on a list and scrolling the list, it always creates fat Full Snapshot Record, instead of Incremental Records. Seeing this in console:
```
Failed to create incremental record: typeMismatch
```

2023-07-04 08:54 UTC, ncreated approved these changes
🎯 ✨

2023-07-04 08:55 UTC, merged