RUM-1555 Default tracing update
DataDog/dd-sdk-ios pull request #1529
Opened 2023-10-25 16:54 UTC by maciejburda

### What and why?

Adds W3C tracecontext to default configuration along with datadog headers.

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [x] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [ ] Run smoke tests
- [ ] Run tests for `tools/`

2023-10-25 16:55 UTC, maciejburda commented
@ganeshnj Do you think we should quite in the `CHANGELOG.md`?

2023-10-26 11:14 UTC, ganeshnj approved these changes

2023-10-26 11:41 UTC, xgouchet submitted a review, later dismissed

2023-10-26 11:47 UTC, ncreated requested changes
Looks good 👌. However, we change default behaviour, so we must update public API comments with new configuration. The change we introduce here impacts these two APIs:
* https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogTrace/Sources/TraceConfiguration.swift#L100
* https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogRUM/Sources/RUMConfiguration.swift#L268

2023-10-26 11:47 UTC, ncreated commented on DatadogInternal/Sources/NetworkInstrumentation/FirstPartyHosts.swift
>      public init(_ hosts: Set<String>) {
The public API comment for this method is now outdated, it mentions `.datadog`, but not `.tracecontext`:

> Creates a `FirstPartyHosts` instance with the given set of host names by assigning `.datadog` header type to each.

2023-10-26 13:16 UTC, ganeshnj submitted a review, later dismissed

2023-10-26 13:16 UTC, ncreated approved these changes
🚀

2023-10-27 06:49 UTC, ncreated approved these changes

2023-10-27 08:00 UTC, ganeshnj approved these changes

2023-10-27 08:06 UTC, merged