RUM-3284 Extension file lock crash
DataDog/dd-sdk-ios pull request #1789
Opened 2024-04-22 20:48 UTC by maciejburda

### What and why?

As mentioned in the: https://github.com/DataDog/dd-sdk-ios/issues/1690

It appears that we are dealing with https://developer.apple.com/documentation/xcode/sigkill

Quote:
0xdead10cc (3735883980) — pronounced “dead lock”
The operating system terminated the app because it held on to a file lock or SQLite database lock during suspension. Request additional background execution time on the main thread with beginBackgroundTask(withName:expirationHandler:). Make this request well before starting to write to the file in order to complete those operations and relinquish the lock before the app suspends. In an app extension, use beginActivity(options:reason:) to manage this work.

Using the `beginActivity(options:reason:)` could work, but is very likely to fail anyway due to short-lived nature of extensions. The other brainstormed option is preventing SDK from from uploading when run from widget/extension (it would only store events and let the app to the upload work next time it's opened).

### How?

PR pursues option 2, which is more likely to succeed in the long run without bigger refactor.

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [x] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [x] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [ ] Run smoke tests
- [ ] Run tests for `tools/`

2024-04-23 08:54 UTC, maxep requested changes
I have a question and a change request on this one:

**Question: Are we sure that the application has access to the data written by the extension?**

I assume it does but I'm not sure, especially for extensions like keyboard that could be in their own sandbox.

**CR: Extension should prevent initialising an uploader instead.**

Here, we add the `isExtension` boolean to the core context and we wait for the first upload cycle to check if we are in an extension.
We could take that decision earlier, during the SDK init and prevent initialising a `FeatureUpload` if we are in an extension.
The core stores could take an optional upload:
```swift
   var stores: [String: (
        storage: FeatureStorage,
        upload: FeatureUpload?
    )] = [:]
```

This way we won't keep an upload instance in memory with its associated queue. WDYT?

2024-04-23 09:07 UTC, ncreated requested changes
We need confirmation if "data sharing" is indeed enabled by default ([Apple docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) seem to contradict this). If it's not, we can't follow with this change as it will disable SDK functionality in default app extensions.

---

About the original issue (crash on accessing files in extension), I think this piece from [Apple guide](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) might be touching on the problem we may need to address:

> When you set up a shared container, the containing app—and each contained app extension that you allow to participate in data sharing—have read and write access to the shared container. To avoid data corruption, you must synchronize data accesses.
>
> Use Core Data, SQLite, or Posix locks to help coordinate data access in a shared container.
>
> In iOS 9 and later, you can employ the [NSFileCoordinator](https://developer.apple.com/documentation/foundation/nsfilecoordinator) class directly for shared data access,

2024-04-23 09:07 UTC, ncreated commented on DatadogCore/Sources/Core/Upload/DataUploadWorker.swift
> +            }
blocking-til-confirmation/ Is SDK's write & read location shared between app and extension uniformly? What is written in [App Extension Programming Guide](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) seems to contradict it:

> #### Sharing Data with Your Containing App
> Even though an app extension bundle is nested within its containing app’s bundle, the running **app extension and containing app have no direct access to each other’s containers**.

"Data sharing" can be enabled **optionally** as an extra entitlement granted to the app. We can't assume every app with extension does it:

> You can, however, enable data sharing. For example, you might want to allow your app extension and its containing app to share a single large set of data, such as prerendered assets.
>
> To enable data sharing, use Xcode or the Developer portal to enable app groups for the containing app and its contained app extensions. Next, register the app group in the portal and specify the app group to use in the containing app. To learn about working with app groups, see [Adding an App to an App Group](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW19).

Looking at [App Groups docs](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW19), it appears that only the `com.apple.security.application-groups` can enable sharing `caches/` location where SDK stores data:

> The `com.apple.security.application-groups` ... allows multiple apps produced by a single development team to share access to a special group container. This container is intended for content that is not user-facing, such as shared **caches** or databases.

---

There are multiple layers of data sharing to consider in order to validate this change. Once confirmed, we should document this decision in the PR description so we're clear on assumptions we take.

2024-04-23 18:05 UTC, maciejburda commented on CHANGELOG.md
> +- [FIX] Fix crash when extension targets. See [#1789][]
Good point! Will add exact description of the change 🙇

2024-04-24 16:23 UTC, maciejburda commented
Thanks for the reviews and some great pointers!
I've made some tests without shared app group and unfortunately it does not upload events.

I'm closing this PR. I'll work on another one that leverages `beginActivity(options:reason:)` API to mitigate these kind of crashes.

2024-04-24 16:23 UTC, closed without merging