feat: send retry information
DataDog/dd-sdk-ios pull request #1991
Opened 2024-08-08 13:04 UTC by ganeshnj

### What and why?

A short description of what changes this PR introduces and why.

### How?

A brief description of implementation details of this PR.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

2024-08-13 08:13 UTC, ncreated requested changes
The concept looks very good in overall 👌, but I left few notes on implementation details, some blocking. Let me know WDYT 🙂!

2024-08-13 08:13 UTC, ncreated commented on DatadogInternal/Sources/Extensions/URL+QueryItem.swift
change-request/ This file duplicates a lot of elements from existing [`URLRequestBuilder`](https://github.com/DataDog/dd-sdk-ios/blob/088d1918faac5f89c2e8b7c801d17f5a7c57b315/DatadogInternal/Sources/Upload/URLRequestBuilder.swift). The `URLRequestBuilder` is more comprehensive and structured way of building `URLRequests` within the SDK and we should prefer it over adding free-form helper functions if possible.

If we can't use `URLRequestBuilder`, we shouldn't be at least exposing these functions to other features through `DatadogInternal`. They should belong to `DatadogCore` otherwise this can end-up in diverging from centralized `URLRequestBuilder` and spreading custom request formatting code among the codebase.

Ideally tho, because `URLRequestBuilder` implements both headers and query items formatting, the new elements introduced in this PR could be somehow part of it. I can imagine the [`FeatureRequestBuilder`](https://github.com/DataDog/dd-sdk-ios/blob/088d1918faac5f89c2e8b7c801d17f5a7c57b315/DatadogInternal/Sources/Upload/FeatureRequestBuilder.swift) protocol to return builder instance rather than already-baked `request`. This way `DatadogCore` could configure additional elements using the builder and only the call the final `build()` to produce `URLRequest`.

// cc @maxep as co-author of this foundation

2024-08-13 08:20 UTC, ganeshnj commented on DatadogCore/Sources/Core/Upload/DataUploader.swift
> +        }
Yes, RFC only talks about the RUM but this is something which applies in general to all POST endpoint which ends up creating some resources (RUM event, trace or log). I don't see any issue sending it to all POST requests that the SDK makes.

But I also like the suggestion to keep for RUM only and we can expand it whenever we want. To save some CPU cycles.

2024-08-13 11:31 UTC, ganeshnj commented on DatadogInternal/Sources/Extensions/Data+Crypto.swift
I still think the method must be in its own file as we are not creating a global method but an extension to data but sure, this can be place next to Cryptography.swift.

2024-08-13 11:53 UTC, ganeshnj commented on DatadogCore/Sources/Core/Upload/DataUploadStatus.swift
> +            responseCode: (networkError as NSError).code,
fair call, I just reverted the change and added extra test case.

2024-08-14 10:51 UTC, ganeshnj commented on DatadogInternal/Sources/Extensions/URL+QueryItem.swift
Ok, now we are fully using the `FeatureRequestBuilder` although this leaks injection of retry headers to each request builders which I don't like but that's the only cleaner way to reuse what we have. 

At some point we might want to change the signature of the request builder to return a builder type which can further be updated without a lot of mutations of Swift types.

2024-08-14 10:52 UTC, ganeshnj commented on DatadogInternal/Sources/Extensions/Data+Crypto.swift
Had to move back to Internal because Core is not directly used in the features and adding sha1 is feature specific.

2024-08-19 12:48 UTC, ncreated submitted a review, later dismissed

2024-08-21 08:17 UTC, ncreated approved these changes

2024-08-21 09:07 UTC, merged