RUMM-812 Shopist: RUM Autoinstrumentation
DataDog/dd-sdk-ios pull request #282
Opened 2020-10-14 15:59 UTC by buranmert

### What and why?

We test RUM autoinstrumentation in Shopist app

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2020-10-15 14:49 UTC, buranmert commented
Resources volume was low due to caching
Now fixed, retrying... ⏳

2020-10-16 11:05 UTC, ncreated requested changes
Great that we get more with less code 👍. The reason of resources volume drop may be because of starting requests in `viewWillAppear()`. Let's switch to `viewDidAppear()` as pointed out and it should be corrected. Once we improve this in SDK, we can switch to "will" again.

2020-10-16 11:05 UTC, ncreated commented on Shopist/Shopist/Scenes/CheckoutViewController.swift
>      override func viewWillAppear(_ animated: Bool) {
We should use `viewDidAppear()`, to get the correct resources assignment.

2020-10-16 11:05 UTC, ncreated commented on Shopist/Shopist/Scenes/ListViewController.swift
>      override func viewWillAppear(_ animated: Bool) {
Same: we should use `viewDidAppear()`, to get the correct resources assignment

2020-10-16 11:05 UTC, ncreated commented on Shopist/Shopist/Scenes/ProductViewController.swift
>      override func viewWillAppear(_ animated: Bool) {
Same: we should use `viewDidAppear()`, to get the correct resources assignment

2020-10-16 14:14 UTC, buranmert commented
<img width="1292" alt="after-v3" src="https://user-images.githubusercontent.com/1417500/96269404-9e628800-0fca-11eb-92ce-f3792536a4f0.png">

now looks good ✅

2020-10-19 07:57 UTC, ncreated approved these changes

2020-10-20 11:00 UTC, merged