Make trace propagation HTTP headers available to ObjC
DataDog/dd-sdk-ios pull request #421
Opened 2021-02-19 02:53 UTC by ben-yolabs

Create `tracePropagationHTTPHeaders` property exposed to ObjC in `DDHTTPHeadersWriter`

### What and why?

As per iOS Trace Collection, users of the SDK may want to manually propagate traces, rather than relying on interceptors provided by the SDK.

Trace propagation HTTP headers are not accessible via `DDHTTPHeadersWriter`, the Objective-C variant/facade class to `HTTPHeadersWriter`.

A `DDHTTPHeadersWriter`'s underlying `HTTPHeadersWriter.tracePropagationHTTPHeaders` should be accessible through a public property exposed to Objective-C.

Resolves #420. 

### How?

Create `tracePropagationHTTPHeaders` property exposed to ObjC in `DDHTTPHeadersWriter`

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-02-19 12:25 UTC, ncreated requested changes
Thanks for fixing this @ben-yolabs 👌. Indeed, we haven't exposed this to obj-c (🐞).

It wasn't noticed before, because we have a mistake in our tests. Please update it as well, then it will look good for me:

```swift
// in `DDTracerTests.swift`

func testInjectingSpanContextToValidCarrierAndFormat() throws {
   // ...

   let objcWriter = DDHTTPHeadersWriter()
   
   // ...

   let expectedHTTPHeaders = [
      "x-datadog-trace-id": "1",
      "x-datadog-parent-id": "2",
   ]

   let swiftWritter = objcWriter.swiftHTTPHeadersWriter
   // 🐞 Here ⬇️  we should be asserting on `objcWriter`, not `swiftWriter`
   XCTAssertEqual(swiftWritter.tracePropagationHTTPHeaders, expectedHTTPHeaders)
 }

```

2021-02-22 18:56 UTC, ben-yolabs commented
@ncreated Requested changed incorporated.

2021-02-23 09:47 UTC, ncreated approved these changes
Excellent, LGTM 👍

2021-02-23 09:50 UTC, buranmert approved these changes

2021-02-23 09:53 UTC, merged