added docs for data collected in iOS
DataDog/dd-sdk-ios pull request #437
Opened 2021-03-08 22:40 UTC by priyanshi-gupta

### What and why?

Adds docs for metrics and attributes collected by iOS SDK.

### How?

Referenced from in-code, view schemas

### Review checklist

- [ ] Make sure all the attributes are covered
- [ ] Make sure each attribute description makes sense in mobile (iOS) context

2021-03-09 14:03 UTC, apigirl commented on docs/mobile_data_collected.md
> +| View       | View represents a unique screen (or screen segment) on your mobile application. Individual ViewControllers are classified as distinct views. While a user stays on a view, RUM event att
```suggestion
| View       | View represents a unique screen (or screen segment) on your mobile application. Individual `ViewControllers` are classified as distinct views. While a user stays on a view, RUM event attributes (Errors, Resources, Actions) get attached to the view with a unique `view.id`                                   |
```

2021-03-09 14:04 UTC, apigirl commented on docs/mobile_data_collected.md
> +| Resource   | Resource represents network requests to first-party hosts, APIs, 3rd party providers and libraries in your mobile application. All requests generated during a user session are attached
```suggestion
| Resource   | Resources represents network requests to first-party hosts, APIs, 3rd party providers, and libraries in your mobile application. All requests generated during a user session are attached to the view with a unique `resource.id`                                                      |
```

2021-03-09 14:05 UTC, apigirl commented on docs/mobile_data_collected.md
> +| Metric                              | Type        | Decription                                                                                          |
```suggestion
| Metric                              | Type        | Description                                                                                          |
```

2021-03-09 14:06 UTC, apigirl commented on docs/mobile_data_collected.md
> +### Common Core Attributes
```suggestion
### Common core attributes
```

2021-03-09 14:07 UTC, apigirl commented on docs/mobile_data_collected.md
> +### Global User Attributes
```suggestion
### Global user attributes
```

2021-03-09 14:07 UTC, apigirl commented on docs/mobile_data_collected.md
> +## Event Specific Metrics and Attributes
```suggestion
## Event specific metrics and attributes
```

2021-03-09 14:07 UTC, apigirl commented on docs/mobile_data_collected.md
> +### View Metrics
```suggestion
### View metrics
```

2021-03-09 14:07 UTC, apigirl commented on docs/mobile_data_collected.md
> +### Resource Metrics
```suggestion
### Resource metrics
```

2021-03-10 11:48 UTC, ncreated requested changes
Nice write up @priyanshi-gupta 💪. I left feedback, let's run next iteration 👍.

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| Event Type | Description
This table seems broken when I [preview its GH rendered page](https://github.com/DataDog/dd-sdk-ios/blob/priyanshi/data_collected/docs/mobile_data_collected.md).

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| View       | View represents a unique screen (or screen segment) on your mobile application. Individual ViewControllers are classified as distinct views. While a user stays on a view, RUM event att
Suggesting further change: `ViewController` → `UIViewController`
```suggestion
| View       | View represents a unique screen (or screen segment) on your mobile application. Individual `UIViewControllers` are classified as distinct views. While a user stays on a view, RUM event attributes (Errors, Resources, Actions) get attached to the view with a unique `view.id`                                   |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| Error     | Error represents an exception or crash (fatal error) emitted by the mobile application attached to the view it is generated in.
`fatal error` may be misunderstood due to `fatalError()` Swift function causing a particular type of crash. I'd remove it at all and not specify what is a "crash" (every iOS dev knows that).
```suggestion
| Error     | Error represents an exception or crash emitted by the mobile application attached to the view it is generated in.                                                                                                                                            |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| Action   | Action represents user activity in your mobile application (application launch, tap, swipe, back etc). Each action is attached with a unique `action_id` attached to the view it gets gene
For the sake of consistency with `view.id` and `resource.id` mentioned earlier:
```suggestion
| Action   | Action represents user activity in your mobile application (application launch, tap, swipe, back etc). Each action is attached with a unique `action.id` attached to the view it gets generated in.                                                                                                                                                |             
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `view.url` | string | URL of the initial view corresponding to the event. |
`view.url` is automatically computed from `UIViewController's` class name, so:
```suggestion
| `view.url` | string | Name of the `UIViewController` class corresponding to the event. |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `view.name` | string | Name of the initial view corresponding to the event. |
To make it more explanatory (`view.name` can be customized by the developer and it defaults to `view.url` if not):
```suggestion
| `view.name` | string | Custom name of the view corresponding to the event. |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `service` | string | The [unified service name][] for this application used to corelate user sessions. |
`[]` missing the link here, no?

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `connectivity.status` | string | Status of device connectivity (`connected`, `not connected`, `maybe`). |
"Network reachability" is a common term for iOS developers.
```suggestion
| `connectivity.status` | string | Status of device network reachability (`connected`, `not connected`, `maybe`). |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `view.time_spent`                             | number (ns) | Time spent on the current view.
```suggestion
| `view.time_spent`                             | number (ns) | Time spent on the this view.                                                                                                                                                                                                  |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `view.is_active`      |    boolean   | Indicates whether the View corresponding to this event is considered active
As we lowercase "view" everywhere else:
```suggestion
| `view.is_active`      |    boolean   | Indicates whether the view corresponding to this event is considered active                                                                                       
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `resource.ssl.duration`        | number (ns)    | Time spent for the TLS handshake. If the last request is not over HTTPS, this metric does not appear (connectEnd - secureConnectionStart) |
It's not true for the iOS SDK:
```suggestion
| `resource.ssl.duration`        | number (ns)    | Time spent for the TLS handshake. |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `resource.first_byte.duration` | number (ns)    | Time spent waiting for the first byte of response to be received (responseStart - RequestStart)                                           |
```suggestion
| `resource.first_byte.duration` | number (ns)    | Time spent waiting for the first byte of response to be received (responseStart - requestStart)                                           |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `resource.type`                | string | The type of resource being collected (for example, `xhr`, `image`, `font`, `CSS`, `Javascript`).          |
```suggestion
| `resource.type`                | string | The type of resource being collected (for example, `xhr`, `image`, `font`, `css`, `js`).          |
```

2021-03-10 11:48 UTC, ncreated commented on docs/mobile_data_collected.md
> +| `action.error.count`      | number      | Count of all errors collected for this action.|
"collected by" sounds technical. The user observation is IMO better expressed by "issued by" (as the action may result with resource start or error occurrence):
```suggestion
| `action.resource.count`         | number      | Count of all resources issued by this action. |
| `action.error.count`      | number      | Count of all errors issued by this action.|
```

2021-03-23 15:31 UTC, ncreated approved these changes

2021-03-23 20:05 UTC, merged