RUMM-1206 Make `DatadogCrashReporting` static in `Package.swift`
DataDog/dd-sdk-ios pull request #449
Opened 2021-03-24 17:04 UTC by ncreated

### What and why?

📦 This PR adds necessary change for linking `DatadogCrashReporting` in `Package.swift`
```diff
-            type: .dynamic,
+            type: .static,
```

### How?

This change is required to avoid following compiler errors in the apps using both `DatadogStatic` and `DatadogCrashReporting`:
```
Swift package product 'Kronos' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
Swift package target '_Datadog_Private' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
Swift package target 'Datadog' is linked as a static library by 'SPMProject' and 'Datadog'. This will result in duplication of library code.
```

From now on, to use Datadog crash reporting feature, apps must link `DatadogStatic` along with `DatadogCrashReporting`:

<img width="539" alt="Screenshot 2021-03-24 at 18 03 26" src="https://user-images.githubusercontent.com/2358722/112352674-404d7580-8ccb-11eb-8ab3-154dd9165d4d.png">

This PR also updates `SPMProject` with the above setup.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-03-25 18:13 UTC, ruthnaebeck requested changes
Docs review

2021-03-25 18:13 UTC, ruthnaebeck commented on dependency-manager-tests/spm/README.md
> +This will create the `SPMProject.xcodeproj` from `SPMProject.xcodeproj.src` by replacing the `REMOTE_GIT_BRANCH` string with the name of the remote branch.
```suggestion
This creates the `SPMProject.xcodeproj` from `SPMProject.xcodeproj.src` by replacing the `REMOTE_GIT_BRANCH` string with the name of the remote branch.
```

2021-03-25 18:13 UTC, ruthnaebeck commented on dependency-manager-tests/spm/README.md
> +Launch the `SPMProject.xcodeproj` to check if SPM is able to fetch `Datadog` package from remote and build the project.
```suggestion
Launch the `SPMProject.xcodeproj` to check if SPM is able to fetch the `Datadog` package from remote and build the project.
```

2021-03-25 18:13 UTC, ruthnaebeck commented on dependency-manager-tests/spm/README.md
> +If you need to update the setup in `SPMProject.xcodeproj`, use:
```suggestion
To update the setup in `SPMProject.xcodeproj`, use:
```

2021-03-25 18:13 UTC, ruthnaebeck commented on dependency-manager-tests/spm/README.md
> +to apply it back to the `SPMProject.xcodeproj.src`, so it can be committed to git.
```suggestion
to apply the change back to the `SPMProject.xcodeproj.src`, so it can be committed to git.
```

2021-03-26 10:43 UTC, buranmert approved these changes
that makes me think maybe we should've made `Datadog, type: static` by default while providing `DatadogDynamic` as an alternative. 
we can consider this for v2.0, i'm taking a note

2021-03-30 06:30 UTC, merged