RUMM-1204 Linter not run for carthage builds
DataDog/dd-sdk-ios pull request #450
Opened 2021-03-26 18:03 UTC by buranmert

### What and why?

`Datadog.xcodeproj` has `Run linter` build phase.
Our SPM&cocoapods users don't see `xcodeproj` but our carthage users build the framework from it.

They don't need to lint our framework's source.

### How?

### Skip linting for `carthage`

`carthage` passes `CARTHAGE=YES` flag to `xcodebuild`, our `Run linter` build phase checks this flag and it skips linting for `carthage` builds.

### Lint once

In addition to `Run linter` build phase, we were also running the linter as a CI step.
Now we run linter only from the build phase, if it fails CI fails at `run_unit_tests` step.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-03-26 18:52 UTC, buranmert commented
I succeeded to fail in CI ✅ 
I'm reverting the change in `Datadog.swift` 🔙

2021-03-29 09:14 UTC, ncreated requested changes
Using `$CARTHAGE == YES` to exclude linter for Carthage builds looks good 👌, but the changes made to `bitrise.yml` introduce very odd setup:
* the `run_unit_tests` step may fail due to linter issue in SDK code or tests,
* the `run_unit_tests` step may fail due to linter issue in other tools code or tests (e.g. bad formatting in `api-surface` tests),
* as we retry `run_unit_tests` step upon failure, it will be run twice on linter issue.

If we want to run linter only once on CI, this should be run as part of `run_linter` step, not `run_unit_tests`. Excluding linter from `run_unit_tests` sounds OK, but in this PR we're removing the entire `run_linter`.

2021-03-29 09:14 UTC, ncreated commented on bitrise.yml
> -        - reporter: emoji
Those steps were linting more than SDK code, see linter configuration:
```yml
# tools/lint/sources.swiftlint.yml:

  - instrumented-tests/http-server-mock/Sources
  - tools/api-surface/Sources
  - tools/api-surface/Fixtures/Sources
  - tools/rum-models-generator/Sources
  - tools/rum-models-generator/Tests/rum-models-generator-coreTests/Fixtures/Output # lint generation fixture
  - dependency-manager-tests/carthage/CTProject
  - dependency-manager-tests/cocoapods/CPProject
  - dependency-manager-tests/spm/SPMProject

# tools/lint/tests.swiftlint.yml:

  - instrumented-tests/http-server-mock/Tests
  - tools/api-surface/Tests
  - tools/rum-models-generator/Tests
  - dependency-manager-tests/carthage/CTProjectTests
  - dependency-manager-tests/carthage/CTProjectUITests
  - dependency-manager-tests/cocoapods/CTProjectTests
  - dependency-manager-tests/cocoapods/CTProjectUITests
  - dependency-manager-tests/spm/SPMProjectTests
  - dependency-manager-tests/spm/SPMProjectUITests
```

Now, these sources are lint as part of  _**"Run unit tests for Datadog - iOS Simulator"**_ which is wrong (we shouldn't fail SDK tests due to linter issue in `rum-models-generator` tool).

2021-03-30 06:28 UTC, ncreated approved these changes
👍 as an optimisation, we could also skip running linter from Xcode build on CI. That might give us `~30s` boost to the job time.

2021-03-30 11:50 UTC, merged