RUMM-1160 Static pod support
DataDog/dd-sdk-ios pull request #451
Opened 2021-03-26 21:09 UTC by buranmert

### What and why?

`DatadogSDK.podspec` requires `!use_frameworks` in client's `Podfile`
Lack of it results in error at `pod install`

### How?: A proposal

For cocoapods and carthage, I can mix Swift and ObjC by importing ObjC headers in framework's umbrella header [as Apple suggests](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)

For Swift Package Manager, this is not possible as mixed targets are not supported. 
To solve this, I pass `SPM_BUILD` flag from `Package.swift` where we create `_Datadog_Private` target.
Now I can `#if SPM_BUILD import _Datadog_Private #endif` in the source code.

### Review checklist

- [ ] Rename ObjC methods so that clients will notice that they are not for public use
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-04-07 17:54 UTC, buranmert commented
ℹ️ CI passed with `use_frameworks`
🗣️ now i'm pushing a commit to remove `use_frameworks`

2021-04-08 11:36 UTC, ncreated requested changes
Looks good 👌 💪 , let's just remove the `Package.resolved`.

2021-04-08 11:36 UTC, ncreated commented on Package.resolved
> +{
This file should be git-ignored 🧽

2021-04-09 08:18 UTC, ncreated approved these changes

2021-04-09 08:28 UTC, merged