RUMM-1439 discard batches on invalid Client Token
DataDog/dd-sdk-ios pull request #535
Opened 2021-07-06 12:09 UTC by xgouchet

### What and why?

When an application is configured with an invalid Client Token, discard the batch to avoid retrying endlessly with the same invalid token.

2021-07-06 12:15 UTC, mariusc83 reviewed
I guess you will need an unit test for this also ?

2021-07-06 14:03 UTC, xgouchet commented
@mariusc83 unfortunately there's no UT already on this mechanism. I'll try and see if I can set it up but it looks that a refactor might be needed to make that class testable :/

2021-07-06 15:07 UTC, mariusc83 approved these changes

2021-07-07 06:37 UTC, ncreated commented
Let's add tests for that as this was a reason why we let this bug enter 🙂. Although it can't be tested directly (it's a private API), we can add two behaviour tests, each observing if the data was deleted / preserved:
* when upload finishes with acceptable code - the file is deleted,
* when upload finishes with server error code - the file is preserved.

We can mock `URLSession` (with our `ServerMock` utility) and let it use real file storage (by using `writer` and `reader` already configured in `DataUploadWorkerTests`):
```swift
func testGivenDataToUpload_whenUploadFinishesWithAcceptableStatusCode_thenDataIsDeleted() {
    func test(statusCode: Int) {
        let server = ServerMock(delivery: .success(response: .mockResponseWith(statusCode: statusCode)))
        let dataUploader = DataUploader(
            urlProvider: .mockAny(),
            httpClient: HTTPClient(session: server.getInterceptedURLSession()),
            httpHeaders: .mockAny()
        )

        // Given
        writer.write(value: ["key": "value"])

        // When
        let worker = DataUploadWorker(
            queue: uploaderQueue,
            fileReader: reader,
            dataUploader: dataUploader,
            uploadConditions: DataUploadConditions.alwaysUpload(),
            delay: DataUploadDelay(performance: UploadPerformanceMock.veryQuick),
            featureName: .mockAny()
        )
        _ = server.waitAndReturnRequests(count: 1)

        // Then
        worker.cancelSynchronously()
        XCTAssertEqual(try temporaryDirectory.files().count, 0, "When status code \(statusCode) is received, data should be deleted")
    }

    test(statusCode: (200...299).randomElement()!)
    test(statusCode: (300...399).randomElement()!)
    test(statusCode: (400...499).randomElement()!)
    test(statusCode: 403)
}

func testGivenDataToUpload_whenUploadFinishesWithServerErrorStatusCode_thenDataIsPreserved() {
    let statusCode = (500...599).randomElement()!
    let server = ServerMock(delivery: .success(response: .mockResponseWith(statusCode: statusCode)))
    let dataUploader = DataUploader(
        urlProvider: .mockAny(),
        httpClient: HTTPClient(session: server.getInterceptedURLSession()),
        httpHeaders: .mockAny()
    )

    // Given
    writer.write(value: ["key": "value"])

    // When
    let worker = DataUploadWorker(
        queue: uploaderQueue,
        fileReader: reader,
        dataUploader: dataUploader,
        uploadConditions: DataUploadConditions.alwaysUpload(),
        delay: DataUploadDelay(performance: UploadPerformanceMock.veryQuick),
        featureName: .mockAny()
    )
    _ = server.waitAndReturnRequests(count: 1)

    // Then
    worker.cancelSynchronously()
    XCTAssertEqual(try temporaryDirectory.files().count, 1, "When status code \(statusCode) is received, data should be preserved")
}
```

2021-07-07 06:41 UTC, ncreated requested changes
Needs tests https://github.com/DataDog/dd-sdk-ios/pull/535#issuecomment-875328938

2021-07-08 10:46 UTC, ncreated approved these changes
LG 🚀

2021-07-09 06:19 UTC, merged