Docs: Rename getting_started file to _index so that it appears on docs site
DataDog/dd-sdk-ios pull request #541
Opened 2021-07-14 16:44 UTC by kayayarai

### What and why?

The docs site is expecting a file called _index.md to be built for https://docs.datadoghq.com/real_user_monitoring/ios/

### How?

Renames getting_started.md to _index.md

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-07-14 16:45 UTC, priyanshi-gupta approved these changes

2021-07-14 19:29 UTC, jtappa requested changes
Since it has already been published as getting_started, it will now need an alias added to the frontmatter so that anyone or anybot that goes there gets redirected to the new location

2021-07-14 19:35 UTC, jtappa approved these changes

2021-07-15 09:22 UTC, buranmert approved these changes

2021-07-15 14:03 UTC, merged