RUMM-1530 Add Datadog.isInitialized variable
DataDog/dd-sdk-ios pull request #566
Opened 2021-08-18 14:24 UTC by maxep

### What and why?

The public interface lacks a way of checking the SDK initialized state.

### How?

A static variable `isInitialized` of the `Datadog` configuration class checks the internal `instance` availability.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-08-18 14:51 UTC, buranmert requested changes
this might break old Xcodes, but otherwise looks good 👍

2021-08-18 14:51 UTC, buranmert commented on Sources/Datadog/Datadog.swift
> +        instance != nil
iirc some previous Xcode/Swift versions don't compile when `return` is omitted.
better safe than sorry: can you please add `return` to this line?

2021-08-18 15:27 UTC, buranmert approved these changes

2021-08-18 15:29 UTC, ncreated approved these changes
Looks good 🚀

2021-08-19 09:47 UTC, xgouchet reviewed
LGTM

2021-08-20 10:36 UTC, merged