RUMM-1350 let customer set up a Proxy for data upload
DataDog/dd-sdk-ios pull request #582
Opened 2021-09-01 10:36 UTC by xgouchet

### What and why?

Let a customer setup a custom Proxy for data intake. 

### How?

A new method let's the customer provide the proxy configuration dictionary that will be forwarded to the HttpClient to create the `URLSession`.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-09-02 07:30 UTC, maxep requested changes
Looks great! 
I've some minor changes to make in the tests implementation: the `as AnyHashable` can be removed when setting the proxy paremeter keys!

2021-09-02 07:30 UTC, maxep commented on Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
> +        ]
All casting `as AnyHashable` are redundant, it is enforced by the dictionary type.
It also valid for all getter in further assertions.

```suggestion
        let proxyConfiguration: [AnyHashable: Any] = [
            kCFNetworkProxiesHTTPEnable: true,
            kCFNetworkProxiesHTTPPort: 123,
            kCFNetworkProxiesHTTPProxy: "www.example.com",
            kCFProxyUsernameKey: "proxyuser",
            kCFProxyPasswordKey: "proxypass",
        ]
```

2021-09-02 07:30 UTC, maxep commented on Tests/DatadogTests/Datadog/Core/FeaturesConfigurationTests.swift
> +        XCTAssertEqual(configuration.common.proxyConfiguration?[kCFNetworkProxiesHTTPEnable as AnyHashable] as? Bool, true)
```suggestion
        XCTAssertEqual(configuration.common.proxyConfiguration?[kCFNetworkProxiesHTTPEnable] as? Bool, true)
```

2021-09-02 07:30 UTC, maxep commented on Tests/DatadogTests/DatadogObjc/DDConfigurationTests.swift
> +        objcBuilder.set(proxyConfiguration: [kCFNetworkProxiesHTTPEnable as AnyHashable: true, kCFNetworkProxiesHTTPPort as AnyHashable: 123, kCFNetworkProxiesHTTPProxy as AnyHashable: "www.example.c
/nit
```suggestion
        objcBuilder.set(proxyConfiguration: [
            kCFNetworkProxiesHTTPEnable: true, 
            kCFNetworkProxiesHTTPPort: 123, 
            kCFNetworkProxiesHTTPProxy: "www.example.com", 
            kCFProxyUsernameKey: "proxyuser", 
            kCFProxyPasswordKey: "proxypass"
        ])
```

2021-09-03 06:56 UTC, maxep approved these changes
👌

2021-09-03 07:24 UTC, ncreated approved these changes

2021-09-03 18:11 UTC, sarina-dd commented on docs/rum_collection/advanced_configuration.md
> +## Configuring a custom Proxy for Datadog data upload
```suggestion
## Configuring a custom proxy for Datadog data upload
```

2021-09-03 18:13 UTC, sarina-dd approved these changes
Small edit suggestion, otherwise LGTM!

2021-09-06 09:54 UTC, merged