RUMM-1455 Add Session Start Callback
DataDog/dd-sdk-ios pull request #590
Opened 2021-09-06 18:08 UTC by maxep

### What and why?

Adds an optional `onSessionStart` callback to `RUMApplicationScope` to be called when a new session starts. The callback takes 2 arguments: the newly started Session ID and a boolean indicating whether or not the session is discarded by the sampling rate (when `true` it means no event in this session will be kept).

Fix #526

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-09-06 18:09 UTC, maxep commented
This PR also surface API from recent PRs.

2021-09-07 09:02 UTC, ncreated requested changes

2021-09-07 09:02 UTC, ncreated commented on Sources/Datadog/DatadogConfiguration.swift
> +            public func onSessionStart(_ handler: @escaping (String, Bool) -> Void) -> Builder {
- [ ] About the naming - as this is a RUM feature, I think it's worth expressing it from the name as we do for other RUM options. How about `onRUMSessionStart`?
- [ ] About testing - it also requires updating tests in [`DatadogConfigurationBuilderTests`](https://github.com/DataDog/dd-sdk-ios/blob/f571f041edb2b1097b6c4fd28bdcdfdf2408ca66/Tests/DatadogTests/Datadog/DatadogConfigurationBuilderTests.swift#L15) (we cover all public options in there)

2021-09-07 09:27 UTC, maxep commented on Sources/Datadog/RUM/RUMMonitor/Scopes/RUMApplicationScope.swift
> +        sessionScopeDidUpdate(refreshedSession)
Yes, I agree 👍

2021-09-07 11:08 UTC, merged

2023-03-15 20:20 UTC, michaelhandkins commented
Hey guys ✌️ I saw that this PR seemed to be in response to [this post](https://github.com/DataDog/dd-sdk-ios/issues/526) about accessing the session ID in code, but I can't figure out how to set that `onSessionStart` callback. All avenues I've tried say they're internally protected or can't be found.