RUM-1805 Set PLCrashReporter custom path
DataDog/dd-sdk-ios pull request #692
Opened 2021-12-17 13:00 UTC by maxep

### What and why?

Configure `PLCrashReporter` with a custom storage location to `/Library/Caches/com.datadoghq.crash-reporting/v1`.

By setting a custom path, we allow other instances of `PLCrashReporter` to work alongside the SDK without altering the reports.

### How?

Sets the `basePath` property of the [PLCrashReporterConfig](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporterConfig.h#L185).

The `PLCrashReporter` version has been incremented to `1.10.1` to use the `[PLCrashReporter crashReportPath]` in tests.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [X] Make sure each commit and the PR mention the Issue number or JIRA reference

2021-12-17 16:16 UTC, fuzzybinary approved these changes

2021-12-20 09:02 UTC, ncreated requested changes
Looks all good 👍.

Integration tests might be failing as we also need to update this path [in our persistence helper](https://github.com/DataDog/dd-sdk-ios/blob/9cdb8fe7615949554e8a6af2ddbe2857050fed35/Datadog/Example/Utils/PersistenceHelper.swift#L48-L50) used to ensure clear state for some integration tests.

2021-12-20 13:04 UTC, maxep commented
@ncreated I need further investigation... It doesnt seem to be writing any report in the custom dir 🤔

2021-12-20 14:19 UTC, maxep commented
I actually let PLCR create the subdirectories by just providing the base path (not absolute string as before)

2021-12-20 17:33 UTC, ncreated approved these changes
🚀

2021-12-20 18:00 UTC, merged