RUMM-1955 Multiple calls to trackDatadogEvents handled
DataDog/dd-sdk-ios pull request #739
Opened 2022-01-27 16:41 UTC by buranmert

### What and why?

If `trackDatadogEvents` method is called multiple times, it crashes the app.
The reason is that calling `WKUserContentController.add(messageHandler:, name:)` multiple times with the same `name` crashes the app.

### How?

`trackDatadogEvents` method removes already-added components before adding them.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2022-01-28 11:44 UTC, ncreated requested changes

2022-01-28 11:44 UTC, ncreated commented on Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
> +        }
It's very unclear why we add this handler 5 times. If we want to test that _"given handler already registered, when registering new handler, it removes the previous one"_, this should be a separate test case.

2022-01-28 11:44 UTC, ncreated commented on Sources/Datadog/FeaturesIntegration/WebView/WKUserContentController+Datadog.swift
> +        }
The problem we're solving is that calling `trackDatadogEvents(in:)` more than once results with a crash:
```swift
controller.trackDatadogEvents(in hosts: ["foo.com"])
controller.trackDatadogEvents(in hosts: ["foo.com"]) // 🔥 crash
```

But this solution looks very odd and unobvious: each time the API is called we're removing **all user scripts** and then re-adding all but Datadog one.

Can't we just early return in this API if it was already called?
```swift
func trackDatadogEvents(in hosts: Set<String>) {
   guard !isAlreadyTracked(self) else {
      userLogger.warn("`trackDatadogEvents(in:)` was called more than once for the same WebView. Second call will be ignored. Make sure you call it only once.")
      return
   }

   // ...
}
```

2022-02-01 09:55 UTC, ncreated approved these changes
👌

2022-02-01 09:55 UTC, ncreated commented on Tests/DatadogTests/Datadog/RUM/WebView/WKUserContentController+DatadogTests.swift
> +    func testItAddsUserScriptAndMessageHandlerMultipleTimes() throws {
The implementation of this test is fine, but I don't understand its name - sounds like we expect the controller to add handler multiple times.
```suggestion
    func testWhenAddingMessageHandlerMultipleTimes_itIgnoresExtraOnesAndPrintsWarning() throws {
```

2022-02-01 11:12 UTC, maxep approved these changes

2022-02-01 12:27 UTC, merged