DOCS-3052 iOS Monitoring Edits
DataDog/dd-sdk-ios pull request #741
Opened 2022-01-28 21:45 UTC by alai97

### What and why?

A short description of what changes this PR introduces and why.

### How?

Implements absolute URLs for the doc site and copy nits.

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

2022-01-28 21:57 UTC, apigirl approved these changes

2022-02-01 09:16 UTC, ncreated requested changes
Thanks a lot 🚀💪! I left two feedbacks on (potentially) broken links.

2022-02-01 09:16 UTC, ncreated commented on docs/rum_collection/advanced_configuration.md
> +In addition to the [default RUM attributes][6] captured by the mobile SDK automatically, you can choose to add additional contextual information, such as custom attributes, to your RUM events to enri
I think the link is broken, should be:
```suggestion
In addition to the [default RUM attributes][7] captured by the mobile SDK automatically, you can choose to add additional contextual information, such as custom attributes, to your RUM events to enrich your observability within Datadog. 
```

Changes to links in this PR:
```diff
- [11]: /real_user_monitoring/ios/data_collected?tab=session#default-attributes
+ [6]: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces?tab=browserrum
+ [7]: https://docs.datadoghq.com/real_user_monitoring/ios/data_collected?tab=session#default-attributes
```

2022-02-01 09:16 UTC, ncreated commented on docs/rum_collection/advanced_configuration.md
> +This tracks all requests sent with the instrumented `session`. Requests matching the `example.com` domain are marked as "first party" and tracing information is sent to your backend to [connect the R
The link seems broken, it should be IMO:
```suggestion
This tracks all requests sent with the instrumented `session`. Requests matching the `example.com` domain are marked as "first party" and tracing information is sent to your backend to [connect the RUM resource with its Trace][6].
```

Changes to links in this PR:
```diff
- [10]: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces?tab=browserrum
+ [6]: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces?tab=browserrum
+ [7]: https://docs.datadoghq.com/real_user_monitoring/ios/data_collected?tab=session#default-attributes
```

2022-02-02 20:19 UTC, ncreated approved these changes
🚀 Thanks, I appreciate all the help on docs!

2022-02-03 07:38 UTC, xgouchet approved these changes

2022-02-04 00:52 UTC, merged