Release 1.10.0-beta1
DataDog/dd-sdk-ios pull request #786
Opened 2022-03-22 13:32 UTC by maxep

### What and why?

Prepares `1.10.0-beta1` release 🚀

This version expose web-view tracking apis.

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [x] Add CHANGELOG entry for user facing change.

2022-03-22 20:18 UTC, alai97 requested changes
Numbered links need to be in brackets [].

2022-03-22 20:18 UTC, alai97 commented on docs/log_collection.md
> +Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox](6), which can't be read by any other app installed on the device.
```suggestion
Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox][6], which can't be read by any other app installed on the device.
```

2022-03-22 20:18 UTC, alai97 commented on docs/rum_collection/data_collected.md
> +Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox](3), which can't be read by any other app installed on the device.
```suggestion
Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox][3], which can't be read by any other app installed on the device.
```

2022-03-22 20:18 UTC, alai97 commented on docs/trace_collection.md
> +Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox](11), which can't be read by any other app installed on the device
```suggestion
Before data is uploaded to Datadog, it is stored in cleartext in the cache directory (`Library/Caches`) of your [application sandbox][11], which can't be read by any other app installed on the device.
```

2022-03-22 20:19 UTC, alai97 approved these changes
Looks good for docs!

2022-03-23 08:14 UTC, xgouchet approved these changes

2022-03-23 08:18 UTC, merged