DOCS-3019 Adds iOS Web View Tracking Documentation
DataDog/dd-sdk-ios pull request #812
Opened 2022-04-08 21:00 UTC by alai97

### What and why?

Adds iOS Web View Tracking beta documentation.

### How?

DOCS-3019

### Additional Notes

Preview link in Documentation PR: .

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing change.

2022-04-11 04:17 UTC, urseberry approved these changes

2022-04-11 04:17 UTC, urseberry commented on docs/rum_collection/web_view_tracking.md
> +You can:
```suggestion
You can perform the following:
```

2022-04-11 04:20 UTC, urseberry commented on docs/rum_collection/web_view_tracking.md
> +Your web views appear as events and views in the [RUM Explorer][4]. Filter on your iOS and tvOS applications and click a session. A side panel with a list of events in the session appears.
```suggestion
Your web views appear as events and views in the [RUM Explorer][4]. Filter on your iOS and tvOS applications, and click a session. A side panel with a list of events in the session appears. 
```

2022-04-11 18:09 UTC, ncreated requested changes
I left feedback on _"Update your existing SDK setup"_ - let me know WDYT 🙂.

2022-04-11 18:09 UTC, ncreated commented on docs/rum_collection/web_view_tracking.md
> +   ```
Unlike in Android SDK, the iOS APIs for webview tracking are not part of the SDK setup which we link to in `[3]`. Instead, we provide the two APIs from the snippet. IMO, we should change this section from _"Update your existing SDK setup"_, to something like _"Instrument web view with Datadog"_. We could use markdown to list and explain each API like we do [here](https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/?tab=swift#rum-configuration).

I can propose something like this 🙂:

> ### Instrument your web views
> 
> The latest version of the RUM iOS SDK comes with two APIs, which let you control web view tracking. Both are declared as an extension to [`WKUserContentController`](https://developer.apple.com/documentation/webkit/wkusercontentcontroller):
>
> `trackDatadogEvents(in hosts: Set<String>)`
> : Enables tracking RUM events in this web view for particular `hosts`.
>
> `stopTrackingDatadogEvents()`
> : Disables tracking for this web view. This should be typically called when you are done with given web view and it is about to be deallocated.
>
> Example:
> ```swift
> import WebKit
> import Datadog
>  
> webView.configuration.userContentController.trackDatadogEvents(in: ["example.com"])
> ```

WDYT?

2022-04-14 15:37 UTC, ncreated approved these changes
💪 looks great! As this feature is already available in `1.10.0` (GA), maybe we can rebase this onto `master` before merge?

2022-04-15 09:42 UTC, merged