add background event tracking documentation
DataDog/dd-sdk-ios pull request #840
Opened 2022-05-04 09:00 UTC by priyanshi-gupta

### What and why?

A short description of what changes this PR introduces and why.

### How?

A brief description of implementation details of this PR.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

2022-05-04 21:44 UTC, alai97 requested changes

2022-05-04 21:44 UTC, alai97 commented on docs/rum_collection/_index.md
> +To track events (crashes, network requests etc.) when your application is in the background, i.e. there is no active view, add the following snippet during initialization while setting up Datadog con
```suggestion
You can track events such as crashes and network requests when your application is in the background (for example, no active view is available). 

Add the following snippet during initialization in your Datadog configuration:
```

2022-05-04 21:44 UTC, alai97 commented on docs/rum_collection/_index.md
> +<div class="alert alert-info"><p>Note that tracking background events could lead to additional sessions that might impact billing. For questions contact support@datadoghq.com</p>
```suggestion
<div class="alert alert-info"><p>Tracking background events may lead to additional sessions, which can impact billing. For questions, <a href="https://docs.datadoghq.com/help/">contact Datadog support.</a></p>
```

2022-05-11 08:21 UTC, ncreated requested changes
Looks good 👍, but I left a note on markdown syntax.

2022-05-18 11:30 UTC, ncreated approved these changes

2022-05-18 12:07 UTC, merged